#!/usr/bin/env python3
"""Write the structured-data block into index.html.

    python3 scripts/apply-jsonld.py

One Person node (the entity Google should tie heysamtheman.com and
@hey_samtheman to, via sameAs) and one WebSite node that points at it.
Idempotent: any previous <script type="application/ld+json"> block written by
this script is replaced, not appended.
"""
import io, json, re, sys

PAGE = "index.html"
SITE = "https://heysamtheman.com"

person = {
  "@type": "Person",
  "@id": f"{SITE}/#sam",
  "name": "Sam",
  "alternateName": "Sam The Man",
  "url": f"{SITE}/",
  "image": f"{SITE}/img/og/home.jpg",
  "description": (
    "Multi-sport adventure athlete and content creator. Twenty-one "
    "self-organised expeditions across four continents since 2013, "
    "including Mont Blanc, Aconcagua, Kilimanjaro and the Matterhorn."),
  "knowsLanguage": ["en", "fr"],
  "sameAs": [
    "https://www.instagram.com/hey_samtheman/",
    "https://www.youtube.com/@hey_samtheman",
    "https://ko-fi.com/heysamtheman",
  ],
}

website = {
  "@type": "WebSite",
  "@id": f"{SITE}/#website",
  "url": f"{SITE}/",
  "name": "Sam \U0001F30B Wild Adventures",
  "inLanguage": "en-GB",
  "publisher": {"@id": f"{SITE}/#sam"},
}

graph = {"@context": "https://schema.org", "@graph": [person, website]}

body = json.dumps(graph, indent=2, ensure_ascii=False)
assert "</script" not in body, "JSON would break out of the script tag"

block = (
  "<!-- Structured data. Generated by scripts/apply-jsonld.py - edit there,\n"
  "     not here, or the next run overwrites it. -->\n"
  '<script type="application/ld+json">\n' + body + "\n</script>\n")

src = io.open(PAGE, encoding="utf-8").read()
out = re.sub(
  r'(?:<!-- Structured data\..*?-->\n)?<script type="application/ld\+json">.*?</script>\n',
  "", src, flags=re.S)
if "</head>" not in out:
    sys.exit(f"{PAGE}: no </head>")
out = out.replace("</head>", block + "</head>", 1)
io.open(PAGE, "w", encoding="utf-8").write(out)
print(f"{'rewrote' if out != src else 'no change'}  {PAGE}  ({len(body)} bytes of JSON-LD)")
